### PR TITLE
Removed most autogenerated files + tests 

### PR DESCRIPTION
**Pull request by Kelvinrr**
## ~Don't Merge Yet~

~There still seem to be some auto-generated files in `point_spectra_gui.core` not being cleaned by `setup.py`~

Files have been cleaned out it seems.

### CODE REVIEW

**Comment by tisaconundrum2** [comment]
You shouldn't be cleaning `\core\` just `\ui\`

**Comment by Kelvinrr** [comment]
Any reason for having auto-generated files in core? Is it possible (within our time restrictions) to purge all auto-generated files?

**Comment by tisaconundrum2** [comment]
There are no auto-generated files in Core, if there are, that is a mistake

**Comment by Kelvinrr** [comment]
`core.DataTable.py` and `core.CombineDatasets.py` are two I've found so far, haven't looked too much into the subdirectories.

**Comment by tisaconundrum2** [comment]
Thank you for telling me about that. I've removed that part of the files. These are not autogenerated.

**Pull request merged**
